hub:
  image: selenium/hub
  ports:
    - "4444:4444"
firefox:
  image: selenium/firefox
  links:
    - hub
  expose:
    - "5555"
  ports:
    - "5900:5900"
chrome:
  image: selenium/chrome
  links:
    - hub
  expose:
    - "5555"
  ports:
    - "5901:5900"